<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admissions | All Notices</title>
    <script src="../assets/js/tailwind.js"></script>
    <link rel="icon" type="image/x-icon" href="../assets/images/nitLogo.png">
    </head>
    <body>
        <?php include '../include/header/header.php'; ?>
        <br>
    <h2 class="text-[#921B1F] text-center font-bold text-xl mt-5 mb-2 sm:mt-0 sm:mb-3 md:text-4xl">All Notices</h2>
        <div class="m-2 p-2 lg:m-9 lg:p-5 border rounded-xl">
            <ul class="font-semibold">
                <div class="text-xs md:text-lg flex flex-row items-center p-3 hover:bg-[#EFE3E0] rounded-xl"><li class="flex flex-row items-center w-full gap-2 cursor-pointer transition-colors p-2"><img src="assets/icons/arrow.png" class="h-[20px] w-[20px] lg:h-[24px] lg:w-[24px] " alt="arrow">Registration Notice for Even Semester 2023-24</li><a target="_blank" href="http://nitsikkim.ac.in/documents/admission/Notice/BtechMtechPhD/Notice for Even Semester Registration 2023-24 _Jan-June 2024 session_.pdf"><img src="assets/icons/pdfLogo.png" alt=""  class="basis-[3%] h-7 cursor-pointer hover:scale-110 transition-scale"></a></div>
	            <div class="text-xs md:text-lg flex flex-row items-center p-3 hover:bg-[#EFE3E0] rounded-xl"><li class="flex flex-row items-center w-full gap-2 cursor-pointer transition-colors p-2"><img src="assets/icons/arrow.png" class="h-[20px] w-[20px] lg:h-[24px] lg:w-[24px] " alt="arrow">Notice for Third Semester Registration 2023-2024</li><a target="_blank" href="http://nitsikkim.ac.in/documents/admission/Notice/BtechMtechPhD/Odd sem registration Notice 2023-24.pdf"><img src="assets/icons/pdfLogo.png" alt=""  class="basis-[3%] h-7 cursor-pointer hover:scale-110 transition-scale"></a></div>
                    <ul class="pl-4">
                        <div class="text-xs md:text-lg flex flex-row items-center p-2 hover:bg-[#EFE3E0] rounded-xl"><li class="flex flex-row items-center w-full gap-2 cursor-pointer transition-colors p-2"><img src="assets/icons/arrowLogo.png" class="h-[16px] w-[12px]" alt="arrowLogo">Institute fees structure for B. Tech. Program (Effective only for registration in ODD Semester -2023-24)</li><a href="http://nitsikkim.ac.in/documents/admission/Notice/BtechMtechPhD/Fee B Tech 23-24 odd sem regn.pdf"><img src="assets/icons/pdfLogo.png" alt=""  class="basis-[3%] h-7 cursor-pointer hover:scale-110 transition-scale"></a></div>
	                    <div class="text-xs md:text-lg flex flex-row items-center p-2 hover:bg-[#EFE3E0] rounded-xl"><li class="flex flex-row items-center w-full gap-2 cursor-pointer transition-colors p-2"><img src="assets/icons/arrowLogo.png" class="h-[16px] w-[12px]" alt="arrowLogo">Institute fees structure for M. Tech. Program (Effective only for registration in ODD Semester -2023-24)</li><a href="http://nitsikkim.ac.in/documents/admission/Notice/BtechMtechPhD/Fee M. Tech 23-24 odd sem regn.pdf"><img src="assets/icons/pdfLogo.png" alt=""  class="basis-[3%] h-7 cursor-pointer hover:scale-110 transition-scale"></a></div>
	                    <div class="text-xs md:text-lg flex flex-row items-center p-2 hover:bg-[#EFE3E0] rounded-xl"><li class="flex flex-row items-center w-full gap-2 cursor-pointer transition-colors p-2"><img src="assets/icons/arrowLogo.png" class="h-[16px] w-[12px]" alt="arrowLogo">Institute fees structure for M.Sc. Program (Effective only for registration in ODD Semester -2023-24)</li><a href="http://nitsikkim.ac.in/documents/admission/Notice/BtechMtechPhD/Fee M.Sc 23-24 odd sem regn.pdf"><img src="assets/icons/pdfLogo.png" alt=""  class="basis-[3%] h-7 cursor-pointer hover:scale-110 transition-scale"></a></div>
                    </ul>
                <div class="text-xs md:text-lg flex flex-row items-center p-3 hover:bg-[#EFE3E0] rounded-xl"><li class="flex flex-row items-center w-full gap-2 cursor-pointer transition-colors p-2"><img src="assets/icons/arrow.png" class="h-[20px] w-[20px] lg:h-[24px] lg:w-[24px] " alt="arrow">Notice for Branch Change</li><a target="_blank" href="http://nitsikkim.ac.in/documents/admission/Notice/BTech/Notice for Branch Change 2023.pdf"><img src="assets/icons/pdfLogo.png" alt=""  class="basis-[3%] h-7 cursor-pointer hover:scale-110 transition-scale"></a></div>
  	            <div class="text-xs md:text-lg flex flex-row items-center p-3 hover:bg-[#EFE3E0] rounded-xl"><li class="flex flex-row items-center w-full gap-2 cursor-pointer transition-colors p-2"><img src="assets/icons/arrow.png" class="h-[20px] w-[20px] lg:h-[24px] lg:w-[24px] " alt="arrow">Registration Notice for Odd Sem 2023-24</li><a target="_blank" href="http://nitsikkim.ac.in/documents/admission/Notice/BtechMtechPhD/Odd Semester Registration notice 2023-24 _ B. Tech. 5th, 7th  Sem and PhD_.pdf"><img src="assets/icons/pdfLogo.png" alt=""  class="basis-[3%] h-7 cursor-pointer hover:scale-110 transition-scale"></a></div>
  	            <div class="text-xs md:text-lg flex flex-row items-center p-3 hover:bg-[#EFE3E0] rounded-xl"><li class="flex flex-row items-center w-full gap-2 cursor-pointer transition-colors p-2"><img src="assets/icons/arrow.png" class="h-[20px] w-[20px] lg:h-[24px] lg:w-[24px] " alt="arrow">Notice for collection of Original Marksheet and Degree Certificate</li><a target="_blank" href="http://nitsikkim.ac.in/documents/admission/Notice/BtechMtechPhD/notice for the collection of Marksheet _ degree.pdf"><img src="assets/icons/pdfLogo.png" alt=""  class="basis-[3%] h-7 cursor-pointer hover:scale-110 transition-scale"></a></div>
	            <div class="text-xs md:text-lg flex flex-row items-center p-3 hover:bg-[#EFE3E0] rounded-xl"><li class="flex flex-row items-center w-full gap-2 cursor-pointer transition-colors p-2"><img src="assets/icons/arrow.png" class="h-[20px] w-[20px] lg:h-[24px] lg:w-[24px] " alt="arrow">FORM-V (Application for various certificates and documents).</li><a target="_blank" href="http://nitsikkim.ac.in/documents/admission/Notice/BtechMtechPhD/FORM-V (Application for  various certificates and documents).pdf"><img src="assets/icons/pdfLogo.png" alt=""  class="basis-[3%] h-7 cursor-pointer hover:scale-110 transition-scale"></a></div>
            </ul>
        </div>
        <?php include '../include/footer.php'; ?>
    </body>
</html>

                <!-- <div class="text-xs md:text-lg flex flex-row items-center p-3 hover:bg-[#EFE3E0] rounded-xl"><li class="flex flex-row items-center w-full gap-2 cursor-pointer transition-colors p-2"><img src="assets/icons/arrow.png" class="h-[20px] w-[20px] lg:h-[24px] lg:w-[24px] " alt="arrow"></li><a target="_blank" ><img src="assets/icons/pdfLogo.png" alt=""  class="basis-[3%] h-7 cursor-pointer hover:scale-110 transition-scale"></a></div>
  	            <div class="text-xs md:text-lg flex flex-row items-center p-3 hover:bg-[#EFE3E0] rounded-xl"><li class="flex flex-row items-center w-full gap-2 cursor-pointer transition-colors p-2"><img src="assets/icons/arrow.png" class="h-[20px] w-[20px] lg:h-[24px] lg:w-[24px] " alt="arrow"></li><a target="_blank" ><img src="assets/icons/pdfLogo.png" alt=""  class="basis-[3%] h-7 cursor-pointer hover:scale-110 transition-scale"></a></div>
	            <div class="text-xs md:text-lg flex flex-row items-center p-3 hover:bg-[#EFE3E0] rounded-xl"><li class="flex flex-row items-center w-full gap-2 cursor-pointer transition-colors p-2"><img src="assets/icons/arrow.png" class="h-[20px] w-[20px] lg:h-[24px] lg:w-[24px] " alt="arrow"></li><a target="_blank" ><img src="assets/icons/pdfLogo.png" alt=""  class="basis-[3%] h-7 cursor-pointer hover:scale-110 transition-scale"></a></div> -->


